version: "3"
services:
  test:
    build: .
    ports:
      - "5702"
    container_name: glad-analysis-test
    env_file:
      - dev.env
    environment:
      DEBUG: "True"
      API_VERSION: v1
    command: test
