develop:
  extends:
    file: base.yml
    service: base
  ports:
    - "45733:35730"
  env_file:
    - dev.env
  container_name: glad-analysis-develop
  environment:
    CT_REGISTER_MODE: auto
    ENVIRONMENT: dev
    DEBUG: "True"
    API_VERSION: v1
  command: develop
  volumes:
    - ./gladAnalysis:/opt/gladAnalysis/gladAnalysis
  restart: always
