apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: gfw
  name: glad-analysis-athena
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: glad-analysis-athena
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
